apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    name: redis-pod
    app: kodekloud-kub-course-oct-18
spec:
  containers:
  - name: redis
    image: redis
    ports:
    - containerPort: 6379
