apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    name: worker-app-pod
    app: kodekloud-kub-course-oct-18
spec:
  containers:
  - name: worker-app
    image: dockersamples/examplevotingapp_worker
